language: python

services:
  - docker

install:
  - make deps

script:
  - make lint
  - make test
  - make docker_build
  - make docker_push
  - make test_xunit

deploy:
  provider: heroku
  app: angkrz1
  api_key: ${HEROKU_API_KEY}
